# Generated by Django 5.0.1 on 2024-01-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
    ]
