# Generated by Django 5.0.2 on 2024-02-23 17:28

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cabecalio', models.CharField(max_length=50, verbose_name='Cabeçalio')),
                ('sublinha', models.CharField(max_length=15, verbose_name='Sublinha')),
                ('sobre', models.CharField(max_length=100, verbose_name='Sobre')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 450, 'width': 600}}, verbose_name='Imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
