# Generated by Django 5.0.2 on 2024-02-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargo_sobre_alter_portifolio_options_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Instagram',
            new_name='instagram',
        ),
    ]
