# Generated by Django 5.0.2 on 2024-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_instagram_funcionario_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolio',
            name='sublinha',
            field=models.CharField(max_length=30, verbose_name='Sublinha'),
        ),
    ]
