# Generated by Django 5.0.3 on 2024-03-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='avalicao',
            new_name='avaliacao',
        ),
    ]
