"""refaturando class user

Revision ID: f1ad6b0a6d4a
Revises: 2761c46f7b2a
Create Date: 2024-06-27 20:52:21.889989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ad6b0a6d4a'
down_revision: Union[str, None] = '2761c46f7b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
