# Generated by Django 5.1.2 on 2024-10-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguidor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seguidor',
            name='seguidor',
        ),
        migrations.RemoveField(
            model_name='seguidor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Seguidor',
        ),
    ]
