# Generated by Django 5.1.2 on 2024-11-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_perfil_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='melhor_resposta',
        ),
    ]
