# Generated by Django 5.1.2 on 2024-11-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_pergunta_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='titulo',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='blog.post'),
        ),
    ]
